### PR TITLE
Use iptables rules (works on cellular networks)

### PR DESCRIPTION
**Pull request by teohhanhui**

### CODE REVIEW

**Comment by teohhanhui** [comment]
Can you do:

```sh
iptables --list --table nat
```

**Comment by tfae** [comment]
After a reboot on OP3T the module now works on Wi-Fi. But it still doesn't work on cellular networks.

Here's the result:
`Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
oem_nat_pre  all  --  anywhere             anywhere            

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             anywhere             tcp dpt:domain to:8.8.8.8:53
DNAT       udp  --  anywhere             anywhere             udp dpt:domain to:8.8.8.8:53

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
natctrl_nat_POSTROUTING  all  --  anywhere             anywhere            

Chain natctrl_nat_POSTROUTING (1 references)
target     prot opt source               destination         

Chain oem_nat_pre (1 references)
target     prot opt source               destination         
`

**Comment by teohhanhui** [comment]
This is out of my league. The iptables rules are supposed to intercept all packets (actually, all packets originating from the host—in this case the phone) with a destination port of 53 (the standard port for DNS) and reroute them to Google DNS.

Perhaps we should try with the iptables rules in addition to the prop changes. 😂😂

**Comment by tfae** [comment]
Does it work on your smartphone on both Wi-Fi and cellular networks?
What device, Android version and ROM are you using?

Another interesting fact is that if I have System Settings enabled (I don't know if you are familiar with this feature on CM/LOS based ROMs), the module doesn't work as the required lines aren't added to the table. 🤔

**Comment by teohhanhui** [comment]
Yes, it works for me on both WiFi and cellular network, whereas the original only worked on WiFi for me. Have you tried with both the iptables rules and the prop changes combined?

I'm on Mi A1, Android 7.1.2, stock ROM.

**Comment by tfae** [comment]
With both combined the module doesn't work here.
Even though I will accept your submission as it'll work on devices that somehow support it.

Just one final question: why did you changed the versionCode to 02000000 and the date formats?

**Comment by teohhanhui** [comment]
> With both combined the module doesn't work here.

Okay that's puzzling...

> why did you change the versionCode to 02000000 and the date formats?

Making the world a better place one ISO standard at a time. Hahaha... (It's the ISO8601 date format). As for the version, it's just an attempt to represent semver as an integer. I can revert these changes if you'd like.

**Comment by tfae** [comment]
There's no need. I'm migrating to template v1500 anyway so I'll revert that. ;)
Thank you!

**Pull request merged**
